#!/bin/bash

echo "🔍 Diagnostic ColiSpace Timeline"
echo "=================================="

echo ""
echo "📋 Vérifications à effectuer :"
echo ""

echo "1️⃣ Vérifier que les scripts SQL ont été exécutés dans Supabase :"
echo "   ✅ table 'timeline_steps' existe"
echo "   ✅ table 'coli_spaces' existe"
echo "   ✅ fonction 'get_or_create_coli_space' existe"
echo "   ✅ trigger 'create_timeline_steps_trigger' existe"

echo ""
echo "2️⃣ Vérifier les données dans Supabase :"
echo "   - Aller dans Table Editor > timeline_steps"
echo "   - Vérifier qu'il y a des données pour ton coli_space_id"
echo "   - Si vide, le problème vient de là"

echo ""
echo "3️⃣ Test rapide :"
echo "   - Créer un nouvel espace coli (nouvelle annonce)"
echo "   - Vérifier si la timeline apparaît"
echo "   - Si oui, le problème était les anciennes données"

echo ""
echo "4️⃣ Debug console :"
echo "   - Ouvrir les logs Metro (terminal où tourne l'app)"
echo "   - Chercher les messages 'Timeline chargée depuis la BD' ou 'Aucune étape'"
echo "   - Partager ces logs si la timeline disparaît toujours"

echo ""
echo "🔧 Solutions possibles :"
echo ""
echo "A) Si table timeline_steps vide :"
echo "   - Les scripts SQL n'ont pas été exécutés"
echo "   - Solution : Exécuter database_schema.sql dans Supabase"
echo ""
echo "B) Si table existe mais pas de données pour cet espace :"
echo "   - L'espace coli a été créé avant les scripts SQL"
echo "   - Solution : Supprimer et recréer l'espace coli"
echo ""
echo "C) Si timeline apparaît 1s puis disparaît :"
echo "   - Problème de requête ou de conversion de données"
echo "   - Les logs devraient montrer l'erreur exacte"

echo ""
echo "🎯 ACTION IMMÉDIATE :"
echo "1. Vérifie que database_schema.sql a été exécuté dans Supabase"
echo "2. Vérifie le contenu de la table timeline_steps"
echo "3. Redémarre l'app complètement"
echo "4. Teste avec un nouvel espace coli"

echo ""
echo "📞 Si problème persiste, partage :"
echo "- Les logs de la console Metro"
echo "- Capture d'écran de Supabase > timeline_steps"
echo "- ID de l'espace coli qui pose problème"
